name: continuous
on:
  push:
    paths-ignore:
      - 'docs/**'
      - boot.toml
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

env:
  BST: bst --config buildstream.conf --colors --builders 1
jobs:
  build:
    name: generate cache
    runs-on: self-hosted
    timeout-minutes: 46000
    strategy:
      matrix:
        variant:
          - user
          - devel
    steps:
      - uses: actions/checkout@v1       
      - name: start buildstream build
        run: ${BST} -o variant ${{matrix.variant}} build installer/image.bst

      - name: checkout image
        run: ${BST} -o variant ${{matrix.variant}} checkout installer/image.bst /storage.rlxos.dev/releases/ --force
  
      - name: commit ostree
        run: |
          echo "${{ github.event.head_commit.message }}" > commit_body
          VARIANT=${{matrix.variant}} BRANCH="${GITHUB_REF##*/}" OSTREE_REPO="/ostree.rlxos.dev" OSTREE_GPG="/gpg.rlxos.dev" make update-ostree
